name: Test on Multiple OS and Browsers

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  browser-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [18, 20, 22]
        browser: [chromium, firefox, webkit]  # You can replace these with the supported browsers

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests on ${{ matrix.browser }}
        run: npx playwright test --browser=${{ matrix.browser }}