name: Test on Multiple OS and Browsers

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  browser-tests:
    runs-on: ${{ matrix.os }}
    strategy:
  fail-fast: false
  matrix:
    os: [ubuntu-latest, macos-latest, windows-latest]
    node-version: [18, 20, 22]
    browser: [chromium, firefox, webkit]
    exclude:
      - os: ubuntu-latest
        browser: webkit
      - os: windows-latest
        browser: webkit

        
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Install browser testing tools (Playwright example)
        run: npx playwright install --with-deps

      - name: Run tests (Playwright example)
        run: |
          echo "Running tests for ${{ matrix.browser }}"
          npx playwright test --project=${{ matrix.browser }}
        env:
          BROWSER: ${{ matrix.browser }}